config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  resources :admins

  # devise_for :admins, controllers: {
  #   sessions: 'users/sessions'
  # }

  # devise_scope :admin do
  #   # Redirests signing out users back to sign-in
  #   get "admins", to: "devise/sessions#new"
  # end

  # get 'classrooms/index'

  root "static_pages#home"

  # get 'sessions/new', as: "log_in"
  
  resources :students do
    member do
      get :profile
    end
    
    collection do
      post :search
    end
  end

  resources :students, only: [:show] do
    resources :terms do
      resources :student_terminal_subjects do
        collection do
          get "time_table", to: "student_terminal_subjects#time_table"
        end
      end
      resources :student_terminal_cocurriculums
    end
  end

  resources :subjects do
    collection do
      get "subjects-excel", to: "subjects#subjects_excel_sheet"
    end
  end

  resources :teachers do
    member do
      get "profile", to: "teachers#profile"
      get "workload", to: "teachers#workload"
    end
  end

  resources :classrooms do
    member do
      post :search_for_attendance
      post :search_for_timetable
    end
    collection do
      get "excel-sheet", to: "classrooms#excel_index"
    end
  end

  resources :student_terminal_subjects, only: [:show] do
    resources :marks_report
  end

  resources :cocurriculums
  
end

app/models/student.rb
class Student < ApplicationRecord
  validates :first_name, :second_name, :last_name,
            :father_name, :mother_name, :d_o_b,
            :contact_one, :city,
            :region, :religion, :qualifications,
            :admission_date, :admission_number,
            presence: true
  validates_uniqueness_of :admission_number

  has_many :terms
  has_many :student_terminal_subjects
  has_many :student_terminal_cocurriculums

  has_one_attached :profile_pic
  
  after_create_commit { broadcast_prepend_to("students_list")}
  after_update_commit { broadcast_update_to("students_list")}

  def total_credits(student)
    credits = 0
    student.student_terminal_subjects.each do |s|
      credits += s.subject.credits
    end
    credits
  end

  def credits_in_current_term(student, term)
    credits = 0
    student_terminal_subjects_in_current_term = student.student_terminal_subjects.where(term_id: term.id)
    student_terminal_subjects_in_current_term.each do |s|
      credits += s.subject.credits
    end
    credits
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
    @students = Student.all.order(first_name: :asc)
  end

  def search
    if params.dig(:first_name_search).present?
      @students = Student.where('first_name ILIKE ?', "%#{params[:first_name_search]}%").order(first_name: :asc)
    else
      @students = Student.all.order(first_name: :asc)
    end

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.update("student_search_list",
          partial: "students/students",
          locals: { students: @students })
        ]
      end
    end
  end

  def show
    @student = Student.find(params[:id])
    @student_terms = @student.terms.order(name: :asc)
    @all_subjects = Subject.all.order(name: :asc)
    respond_to do |format|
      format.html
      format.pdf do
        pdf = StudentPdf.new(@student)
        send_data pdf.render,
          filename: "#{@student.first_name + " " + @student.second_name + " " + @student.last_name}.pdf",
          type: 'application/pdf',
          disposition: 'inline'
      end
    end
    # for producing qr code for the name of each student
    @student_name = @student.first_name + " " + @student.second_name + " " + @student.last_name
    @qrcode = RQRCode::QRCode.new(@student_name)

    # NOTE: showing with default options specified explicitly
    @svg = @qrcode.as_svg(
      color: "444",
      shape_rendering: "crispEdges",
      module_size: 1.5,
      standalone: true,
      use_path: true
    )
    # @png = @qrcode.as_png(
    #   bit_depth: 1,
    #   border_modules: 4,
    #   color_mode: ChunkyPNG::COLOR_GRAYSCALE,
    #   color: "black",
    #   file: nil,
    #   fill: "white",
    #   module_px_size: 6,
    #   resize_exactly_to: false,
    #   resize_gte_to: false,
    #   size: 120
    # )
    # IO.binwrite("/tmp/student.png", @png.to_s)
  end

  def profile
    @student = Student.find(params[:id])
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    if @student.update(student_params)
      redirect_to student_url(@student)
    else
      render :edit
    end
  end

  def new
    @student = Student.new
    @suggested_admission_number = Student.last.admission_number + 1
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to students_url }
      end
    else
      render :new
    end
  end

  private

  def student_params
    params.require(:student).permit(
      :first_name, :second_name, :last_name,
      :father_name, :mother_name, :d_o_b,
      :birth_cert, :contact_one, :contact_two, :city,
      :region, :religion, :qualifications,
      :admission_date, :admission_number, :profile_pic
    )
  end
end

app/helpers/students_helper.rb
module StudentsHelper

end

app/views/students/_count.html.erb
<%= turbo_frame_tag "students_count" do %>
  <span class="px-3 py-3 text-xl text-gray-600 border border-orange-500 rounded-full bg-gray-50"><%= Student.count %></span>
<% end %>

app/views/students/_form.html.erb
<%= form_for student do |f| %>
  <% if student.errors.any? %>
    <ul class="bg-red-200 px-3 py-2 mb-4 border border-red-400 text-red-400 list-disc list-inside">
      <% student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <div class="flex justify-center space-x-3">
    <div class="flex flex-col justify-center space-y-2">
      <div class="border border-blue-400 rounded-lg">
        <div class="px-2 py-4 flex flex-col justify-center space-y-2">
          <h1 class="pb-2 text-gray-800">
            Name
          </h1>
          <%= f.text_field :first_name, placeholder: "First Name", class: "p-1 my-4 border border-zinc-400 rounded-lg text-sm text-gray-700 fonts-normal focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500" %>
          <%= f.text_field :second_name, placeholder: "Second Name", class: "p-1 my-4 border border-zinc-400 rounded-lg text-sm text-gray-700 fonts-normal focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500" %>
          <%= f.text_field :last_name, placeholder: "Third Name", class: "p-1 my-4 border border-zinc-400 rounded-lg text-sm text-gray-700 fonts-normal focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500" %>
        </div>
      </div>
      <% if student.profile_pic.present? %>
        <%= image_tag student.profile_pic, height: 30, width: 30 %>
      <% end %>
      <%= f.label :profile_pic, "Student's Pic", class: "text-gray-800" %>
      <%= f.file_field :profile_pic, class: "text-sm text-gray-700 " %>
      
      <%= f.label :d_o_b, "Date of Birth", class: "text-gray-800" %>
      <%= f.date_field :d_o_b, class: "p-1 my-4 border border-zinc-400 rounded-lg text-sm text-gray-700 fonts-normal focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500" %>
    </div>
    <div class="flex flex-col justify-center space-y-2">
      <%= f.label :father_name, "Father's Name", class: "text-gray-800" %>
      <%= f.text_field :father_name, class: "p-1 my-4 border border-zinc-400 rounded-lg text-sm text-gray-700 fonts-normal focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500" %>

      <%= f.label :mother_name, "Mother's Name", class: "text-gray-800" %>
      <%= f.text_field :mother_name, class: "p-1 my-4 border border-zinc-400 rounded-lg text-sm text-gray-700 fonts-normal focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500" %>

      <%= f.label :birth_cert, "Birth Certificate Available?", class: "text-gray-800" %>
      <%= f.select :birth_cert, ["Available", "Not Available"], {include_blank: " "}, { class: "p-1 my-4 bg-gray-50 border border-zinc-400 rounded-lg text-sm text-gray-700 fonts-normal focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500" }%>
    
      <%= f.label :contact_one, "Contact Number", class: "text-gray-800" %>
      <%= f.text_field :contact_one, class: "p-1 my-4 border border-zinc-400 rounded-lg text-sm text-gray-700 fonts-normal focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500" %>

      <%= f.label :contact_two, "Another Contact Number", class: "text-gray-800" %>
      <%= f.text_field :contact_two, class: "p-1 my-4 border border-zinc-400 rounded-lg text-sm text-gray-700 fonts-normal focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500" %>
    </div>

    <div class="flex flex-col justify-center space-y-2">
      <div class="border border-blue-400 rounded-lg">
        <div class="px-2 py-4 flex flex-col justify-center space-y-2">
          <h1 class="pb-2 text-gray-800">
            Address
          </h1>
          <%= f.text_field :city, placeholder: "City", class: "p-1 my-4 border border-zinc-400 rounded-lg text-sm text-gray-700 fonts-normal focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500" %>
          <%= f.text_field :region, placeholder: "Region", class: "p-1 my-4 border border-zinc-400 rounded-lg text-sm text-gray-700 fonts-normal focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500" %>
        </div>
      </div>
      
      <%= f.label :religion, class: "text-gray-800" %>
      <%= f.select :religion, ["Sunni Muslim", "Shia Muslim", "Christian"], {}, { class: "p-1 my-4 bg-gray-50 border border-zinc-400 rounded-lg text-sm text-gray-700 fonts-normal focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500" } %>

      <%= f.label :qualifications, "Qualification(s), 'Both Hauza and Secular'", class: "text-gray-800" %>
      <%= f.text_field :qualifications, class: "p-1 my-4 border border-zinc-400 rounded-lg text-sm text-gray-700 fonts-normal focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500" %>
    </div>

    <div class="flex flex-col justify-center space-y-2">
      <%= f.label :admission_date, class: "text-gray-800" %>
      <%= f.date_field :admission_date, class: "p-1 my-4 border border-zinc-400 rounded-lg text-sm text-gray-700 fonts-normal focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500" %>
      
      <%= f.label :admission_number, class: "text-gray-800" %>
      <%= f.number_field :admission_number, class: "p-1 my-4 border border-zinc-400 rounded-lg text-sm text-gray-700 fonts-normal" %>
      <% if controller.action_name == "new" %>
        <div class="px-2 text-gray-700 text-sm bg-sky-200">Suggested Admission Number: <%= @suggested_admission_number %></div>
      <% end %>
    </div>
  </div>
  <%= f.submit yield(:button_name), class: "w-full mt-4 bg-blue-600 px-4 py-3 text-gray-50 rounded hover:bg-blue-900" %>
<% end %>

app/views/students/_search_form.html.erb
<%= form_with url: search_students_path, method: :post do |form| %>
  <%= form.search_field :first_name_search, value: params[:first_name_search],
      placeholder: "Search student with first name",
      class: "px-2 py-1 text-gray-600 border border-gray-400 rounded-xl focus:outline-none focus:border-orange-400 focus:ring-1 focus:ring-orange-400",
      oninput: "this.form.requestSubmit()" %>
<% end %>

app/views/students/_search_results.html.erb
<span class="text-gray-700 font-bold">
  <% unless students.empty? %>
    results found:  <%= students.count %>
  <% end %>
</span>
<% students.each do |student| %>
  <br>
  <%= link_to student, data: {"turbo_frame": "_top"}, class: "text-blue-700 px-2 font-bold" do %>
    <%= highlight(student.first_name + " " + student.second_name + " " + student.last_name, params.dig(:first_name_search)) %>
  <% end %>
  <%= link_to students_path(anchor: "student_#{student.id}") do %>
    <i class="fa-solid fa-arrow-down"></i>
  <% end %>
<% end %>

app/views/students/_student.html.erb
<%= turbo_frame_tag(dom_id(student)) do %>
  <div class="px-6 py-2 bg-slate-200 border border-slate-400 rounded shadow-lg hover:shadow-2xl transition delay-100">
    <div class="flex justify-between items-center">
      <%= link_to student_path(student),
          class: "text-lg text-gray-700" do %>
        <i class="fa-solid fa-id-badge"></i>
        <%= student.first_name %>
        <%= student.second_name %>
        <%= student.last_name %>
      <% end %>
      <%= turbo_frame_tag "profile#{student.id}" do %>
        <%= link_to profile_student_path(student), class: "text-sm text-gray-700" do %>
          <i class="fa-solid fa-link"></i> profile
        <% end %>
      <% end %>
    </div> 
  </div>
<% end %>

app/views/students/_students.html.erb
<%= turbo_frame_tag "student_search_list" do %>
  <div class="flex justify-center items-center rounded bg-orange-500 absolute right-7 top-32 z-50">
    <span class="h-10 pl-2 pr-1 py-1 text-lg text-gray-50 flex justify-center items-center">All students</span>
    <%= render "students/count" %>
  </div>

  <div class="w-full mt-3 mb-16 bg-gray-50">
    <%= turbo_stream_from "students_list" %>
    <%= turbo_frame_tag "students" do %>
    <div class="mx-8 flex flex-col space-y-3">
      <% students.each do |student| %>
        <%= render "students/student", student: student %>
      <% end %>
    </div>
    <% end %>
  </div>
<% end %>

app/views/students/create.turbo_stream.erb
<%= turbo_stream.prepend("students", @student) %>
<%= turbo_stream.update("students_count") do %>
  <span class="px-3 py-3 text-xl text-gray-600 border border-orange-500 rounded-full bg-gray-50"><%= Student.count %></span>
<% end %>
<%# <%= turbo_stream.replace("new_student") do %> %>
  <%# <div class="mt-4 flex flex-col items-center"> %>
    <%# <div class=""> %>
      <%# <%= link_to students_url, class: "px-2 py-1 text-lg text-gray-50 bg-blue-600 shadow-xl rounded" do %> %>
        <%# "Done. Click to refresh the page!" %>
      <%# <% end %>
    <%# </div>
  <%# </div>
<%# <% end %>

app/views/students/edit.html.erb
<% provide(:button_name, "Edit Student") %>
<%# <%= turbo_frame_tag(dom_id(@student)) do %>
  <%# <%= render "form", student: @student %>
<%# <% end %>

<%= turbo_frame_tag "modal" do %>
  <div data-controller="form-modal" data-action="turbo:submit-end->form-modal#submitEnd">
    <div class="min-h-screen w-screen bg-black bg-opacity-80 flex justify-center items-center fixed z-10">
      <div class="bg-white bg-opacity-100 px-10 py-6 rounded">
        <%= link_to students_path, class: "mx-2 text-xl text-gray-100 absolute top-10 right-10" do %>
          <i class="fa-solid fa-circle-xmark"></i>
        <% end %>
        <div class="my-4 text-2xl text-gray-700 flex justify-center items-center">Edit Student</div>
        <%= render "form", student: @student  %>
      </div>
    </div>
  </div>
<% end %>

app/views/students/index.html.erb
<%= turbo_frame_tag "admin_list" do %>
  <div class="mt-8 flex flex-col justify-center items-center">
    <%= render "students/search_form" %>
  </div>
  <div class="my-8 flex justify-center items-center">
    <%= link_to new_student_path, data: {turbo_frame: "modal"}, class: "px-3 py-2 bg-green-700 text-2xl text-gray-50 font-light shadow-xl rounded hover:bg-green-400" do %>
      New <i class="fas fa-user-graduate"></i> Student
    <% end %>
  </div>
  <%= render "students/students", students: @students %>
<% end %>

app/views/students/new.html.erb
<% provide(:button_name, "New Student") %>

<%= turbo_frame_tag "modal" do %>
  <div data-controller="form-modal" data-action="turbo:submit-end->form-modal#submitEnd">
    <div class="min-h-screen w-screen bg-black bg-opacity-80 flex justify-center items-center fixed z-10">
      <div class="bg-white bg-opacity-100 px-10 py-6 rounded">
        <%= link_to students_path, class: "mx-2 text-xl text-gray-100 absolute top-10 right-10" do %>
          <i class="fa-solid fa-circle-xmark"></i>
        <% end %>
        <div class="my-4 text-2xl text-gray-700 flex justify-center items-center">New Student</div>
        <%= render "form", student: @student  %>
      </div>
    </div>
  </div>
<% end %>

app/views/students/profile.html.erb
<%= turbo_frame_tag "profile#{@student.id}" do %>
  <div class="flex justify-center items-center text-gray-700">
    <div class="px-2 flex flex-col justify-center items-center">
      <div><u>Father's Name:</u>  
        <%= @student.father_name %>
      </div>
      <div><u>Mother's Name:</u> 
        <%= @student.mother_name %>
      </div>
      <div><u>D.O.B:</u>
        <%= @student.d_o_b %>
      </div>
    </div>

    <div class="px-2 flex flex-col justify-center items-center border-r border-l border-slate-500">
      <div><u>Birth Certificate:</u> 
        <%= @student.birth_cert %>
      </div>
      <div><u>Contact:</u>
        <%= @student.contact_one %>
      </div>
      <div><u>Another Contact:</u> 
        <%= @student.contact_two %>
      </div>
      <div><u>Address:</u>
        <%= @student.city %>,  
        <%= @student.region %>
      </div>
    </div>

    <div class="px-2 flex flex-col justify-center items-center">
      <div><u>Religion:</u> 
        <%= @student.religion %>
      </div>
      <div><u>Qualifications:</u> 
        <%= @student.qualifications %>
      </div>
      <div><u>Admission Date:</u>
        <%= @student.admission_date %>
      </div>
      <div><u>Admission Number:</u>
        <%= @student.admission_number %>
      </div>
    </div>
  </div>

  <div class="mt-4 flex justify-center items-center space-x-2">
    <%= link_to edit_student_path(@student), data: {turbo_frame: "modal" }, class: "px-1 bg-gray-800 rounded-lg text-gray-100 flex justify-center items-center" do %>
      edit
    <% end %>
    <%= link_to students_path, class: "px-1 bg-gray-800 rounded-lg text-gray-100 justify-center items-center" do %>
      close
    <% end %>
  </div>
<% end %>

app/views/students/show.html.erb
<%= turbo_frame_tag(dom_id(@student)) do %>
<div class="border-t-4 border-green-600 rounded-xl text-4xl font-light text-gray-700 flex justify-center items-baseline space-x-7">
  <div class="pt-4 flex flex-row justify-center items-center space-x-3">
    <span><%= @student.first_name %> <%= @student.second_name %> <%= @student.last_name %></span>
    <span class="text-gray-700"><%= @svg.html_safe %></span>
    <% if @student.profile_pic.present? %>
      <span><%= image_tag @student.profile_pic, class: "rounded-full w-16 h-16" %></span>
    <% end %>
  </div>
  <%= link_to "close", students_path, class: "px-2 py-1 rounded bg-gray-700 text-base text-gray-100" %>
</div>

<div class="mt-2 flex justify-center items-center space-x-3">
  <%= link_to new_student_term_path(@student), data: { turbo_frame: "term_new_edit_modal" }, class: "px-2 py-1 bg-gray-600 text-gray-100 rounded" do %>
    <i class="fa-solid fa-link"></i> Add New Term / Entrance / Already Finished
  <% end %>

  <%= link_to student_path(@student, format: :pdf), target: "_blank", class: "px-2 py-1 bg-gray-600 text-gray-100 rounded" do %>
    <i class="fa-solid fa-link"></i> All subjects with marks PDF
  <% end %>
</div>

<div class="py-8 w-full">
  <%= turbo_frame_tag "terms" do %>
    <% if @student.terms.any? %>
      <div class="flex flex-col">
      <% @student_terms.each do |term| %>
        <%= render "terms/term", term: term %>
      <% end %>
      </div>
    <% end %>
  <% end %>
</div>

<div class="pb-4 border-gray-200 flex flex-col justify-center items-center space-y-3">
  <div class="text-xl font-light text-gray-700">Total credits taken by <%= @student.first_name %>: <u><%= @student.total_credits(@student) %>/<%= @all_subjects.sum(:credits) %></u></div>
  <div class="flex justify-center items-center space-x-2">
    <div class="h-6 w-6 bg-gray-300 text-gray-300 rounded-full">#</div>
    <div class="text-gray-700">Not Taken</div>
    <div class="h-6 w-6 bg-blue-600 text-blue-600 rounded-full">#</div>
    <div class="text-gray-700">Taken</div>
    <div class="h-6 w-6 bg-green-600 text-green-600 rounded-full">#</div>
    <div class="text-gray-700">Taken and Passed</div>
    <div class="h-6 w-6 bg-red-600 text-red-600 rounded-full">#</div>
    <div class="text-gray-700">Taken and Failed</div>
  </div>
  <div class="flex justify-center items-center">
    <div class="border-b-4 pb-4 border-green-600 rounded-xl grid grid-cols-5 gap-3">
      <% @all_subjects.each do |sub| %>
        <% if sub.student_terminal_subjects.where(student_id: @student.id).any? %>
          <% sub.student_terminal_subjects.where(student_id: @student.id).each do |subject| %>
            <% if subject.marks_report %>
              <% if subject.marks_report.total < 50 %>
                <div class='px-1 py-1 text-gray-50 flex justify-center items-center rounded bg-red-600'> <%= subject.subject.name + " " + "(" + subject.subject.credits.to_s + ")" %></div>
              <% else %>
                <div class='px-1 py-1 text-gray-50 flex justify-center items-center rounded bg-green-600'> <%= subject.subject.name + " " + "(" + subject.subject.credits.to_s + ")" %></div>
              <% end %>
            <% else %>
              <div class='px-1 py-1 text-gray-50 flex justify-center items-center rounded bg-blue-600'> <%= subject.subject.name + " " + "(" + subject.subject.credits.to_s + ")" %></div>
            <% end %>
          <% end %>
        <% else %>
          <div class='px-1 py-1 text-gray-700 flex justify-center items-center rounded bg-gray-300'> <%= sub.name + " " + "(" + sub.credits.to_s + ")" %></div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<% end %>