config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  resources :admins

  # devise_for :admins, controllers: {
  #   sessions: 'users/sessions'
  # }

  # devise_scope :admin do
  #   # Redirests signing out users back to sign-in
  #   get "admins", to: "devise/sessions#new"
  # end

  # get 'classrooms/index'

  root "static_pages#home"

  # get 'sessions/new', as: "log_in"
  
  resources :students do
    member do
      get :profile
    end
    
    collection do
      post :search
    end
  end

  resources :students, only: [:show] do
    resources :terms do
      resources :student_terminal_subjects do
        collection do
          get "time_table", to: "student_terminal_subjects#time_table"
        end
      end
      resources :student_terminal_cocurriculums
    end
  end

  resources :subjects do
    collection do
      get "subjects-excel", to: "subjects#subjects_excel_sheet"
    end
  end

  resources :teachers do
    member do
      get "profile", to: "teachers#profile"
      get "workload", to: "teachers#workload"
    end
  end

  resources :classrooms do
    member do
      post :search_for_attendance
      post :search_for_timetable
    end
    collection do
      get "excel-sheet", to: "classrooms#excel_index"
    end
  end

  resources :student_terminal_subjects, only: [:show] do
    resources :marks_report
  end

  resources :cocurriculums
  
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  validates_presence_of :full_name, :contact_no, :staff_quarter

  def to_s
    full_name
  end

  has_many :student_terminal_subjects

  after_create_commit { broadcast_append_to("teachers_list")}
  after_update_commit { broadcast_update_to("teachers_list")}
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController

  def index
    @teachers = Teacher.all.order(full_name: :asc)
  end

  def show
    @teacher = Teacher.find(params[:id])
    @teacher_terminal_subjects = @teacher.student_terminal_subjects
    @teacher_terminal_subjects_without_duplication = @teacher_terminal_subjects.uniq do |class_subject|
      # class_subject.subject.name
      # class_subject.term.name
      class_subject.period_time
      # class_subject.classroom.name
    end
    @teacher_name = @teacher.full_name
    @qrcode = RQRCode::QRCode.new(@teacher_name)

    # NOTE: showing with default options specified explicitly
    @svg = @qrcode.as_svg(
      color: "444",
      shape_rendering: "crispEdges",
      module_size: 1.5,
      standalone: true,
      use_path: true
    )
  end

  def profile
    @teacher = Teacher.find(params[:id])
  end
  
  def workload
    @teacher = Teacher.find(params[:id])
    @teacher_terminal_subjects_without_duplication = @teacher.student_terminal_subjects.uniq do |class_subject|
      # class_subject.subject.name
      # class_subject.term.name
      class_subject.period_time
      # class_subject.classroom.name
    end
    render xlsx: "workload", filename: "#{@teacher.full_name}", disposition: 'inline', template: "teachers/workload"
  end

  def edit
    @teacher = Teacher.find(params[:id])
  end

  def update
    @teacher = Teacher.find(params[:id])
    if @teacher.update(teacher_params)
      render @teacher
    else
      render :edit
    end
  end

  def new
    @teacher = Teacher.new
  end

  def create
    @teacher = Teacher.new(teacher_params)
    if @teacher.save
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to teachers_url}
      end
    else
      render :new
    end
  end

  private

  def teacher_params
    params.require(:teacher).permit(:full_name, :contact_no, :full_address, :staff_quarter, :joining_date)
  end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_count.html.erb
<%= turbo_frame_tag "teachers_count" do %>
  <span class="px-3 py-3 text-xl text-gray-600 border border-indigo-500 rounded-full bg-gray-50"><%= Teacher.count %></span>
<% end %>

app/views/teachers/_form.html.erb
<%= form_for teacher, html: { class: "flex flex-col space-y-2" }  do |f| %>
  <% if teacher.errors.any? %>
    <ul class="bg-red-200 px-2 py-1 border border-red-400 text-red-400 list-disc list-inside">
      <% teacher.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <%= f.label :full_name, class: "text-gray-700 font-semibold" %>
  <%= f.text_field :full_name, class: "px-1 py-1 text-gray-700 rounded border border-gray-300 bg-gray-200"%>
  
  <%= f.label :contact_no, class: "text-gray-700 font-semibold" %>
  <%= f.text_field :contact_no, class: "px-1 py-1 text-gray-700 rounded border border-gray-300 bg-gray-200" %>

  <%= f.label :full_address, class: "text-gray-700 font-semibold" %>
  <%= f.text_field :full_address, class: "px-1 py-1 text-gray-700 rounded border border-gray-300 bg-gray-200" %>

  <%= f.label :joining_date, class: "text-gray-700 font-semibold" %>
  <%= f.date_field :joining_date, { class: "p-1 my-4 bg-gray-50 border border-zinc-400 rounded-lg text-sm text-gray-700 fonts-normal focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500" } %>

  <%= f.label :staff_quarter, label: "Residing in staff quarters?", collection: ["Yes", "No"], default: "Yes" %>
  <%= f.select :staff_quarter, ["Yes", "No"], {include_blank: ""}, { class: "p-1 my-4 bg-gray-50 border border-zinc-400 rounded-lg text-sm text-gray-700 fonts-normal focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500" } %>

  <%= f.submit yield(:button_name), class: "w-full bg-blue-700 mt-3 px-3 py-2 text-lg text-gray-50 rounded-lg hover:bg-blue-900" %>
<% end %>

app/views/teachers/_teacher.html.erb
<%= turbo_frame_tag(dom_id(teacher)) do %>
  <div class="px-6 py-2 bg-blue-100 border border-slate-400 rounded shadow-lg hover:shadow-2xl transition delay-100">
    <div class="flex justify-between items-center">
      <%= link_to teacher_path(teacher),
          class: "text-lg text-gray-700" do %>
        <i class="fa-solid fa-user"></i>
        <%= teacher.full_name %>
      <% end %>
      <%= turbo_frame_tag "profile#{teacher.id}" do %>
        <%= link_to profile_teacher_path(teacher), class: "text-sm text-gray-700" do %>
          <i class="fa-solid fa-link"></i> profile
        <% end %>
      <% end %>
    </div> 
  </div>
<% end %>

app/views/teachers/create.turbo_stream.erb
<%= turbo_stream.append("teachers", @teacher) %>
<%= turbo_stream.update("teachers_count") do %>
  Total Number of Teachers: <%= Teacher.count %>
<% end %>

app/views/teachers/edit.html.erb
<% provide(:button_name, "Edit account of the teacher") %>

<%= turbo_frame_tag "teacher_new_edit_modal" do %>
  <div data-controller="form-modal" data-action="turbo:submit-end->form-modal#submitEnd">
    <div class="min-h-screen w-screen bg-black bg-opacity-80 flex justify-center items-center fixed z-10">
      <div class="bg-white bg-opacity-100 px-10 py-6 rounded">
        <%= link_to teachers_path, class: "mx-2 text-xl text-gray-100 absolute top-10 right-80" do %>
          <i class="fa-solid fa-circle-xmark"></i>
        <% end %>
        <div class="my-4 text-2xl text-gray-700 flex justify-center items-center">Edit Teacher</div>
        <%= render "teachers/form", teacher: @teacher %>
      </div>
    </div>
  </div>
<% end %>

app/views/teachers/index.html.erb
<%= turbo_frame_tag "admin_list" do %>
<div class="flex justify-center items-center rounded bg-indigo-500 absolute right-7 top-32 z-50">
  <span class="h-10 pl-2 pr-1 py-1 text-lg text-gray-50 flex justify-center items-center">All teachers</span>
  <%= render "teachers/count" %>
</div>

<div class="mt-16 mb-8 flex justify-center items-center">
  <%= link_to new_teacher_path, data: { turbo_frame: "teacher_new_edit_modal" }, class: "px-3 py-2 bg-green-700 text-2xl text-gray-50 font-light shadow-2xl rounded hover:bg-green-400" do %>
    New <i class="fas fa-chalkboard-teacher"></i> Teacher
  <% end %>
</div>

  <div class="w-full mt-3 mb-16 bg-gray-50"> 
    <%= turbo_stream_from "teachers_list" %>
    <%= turbo_frame_tag "teachers" do %>
      <div class="mx-8 flex flex-col space-y-3">
        <% @teachers.each do |teacher| %>
          <%= render "teachers/teacher", teacher: teacher %>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/teachers/new.html.erb
<% provide(:button_name, "Create account for the teacher") %>

<%= turbo_frame_tag "teacher_new_edit_modal" do %>
  <div data-controller="form-modal" data-action="turbo:submit-end->form-modal#submitEnd">
    <div class="min-h-screen w-screen bg-black bg-opacity-80 flex justify-center items-center fixed z-10">
      <div class="bg-white bg-opacity-100 px-10 py-6 rounded">
        <%= link_to teachers_path, class: "mx-2 text-xl text-gray-100 absolute top-10 right-80" do %>
          <i class="fa-solid fa-circle-xmark"></i>
        <% end %>
        <div class="my-4 text-2xl text-gray-700 flex justify-center items-center">New Teacher</div>
        <%= render "teachers/form", teacher: @teacher %>
      </div>
    </div>
  </div>
<% end %>

app/views/teachers/profile.html.erb
<%= turbo_frame_tag "profile#{@teacher.id}" do %>
  <div class="flex justify-center items-center text-gray-700">
    <div class="px-2 flex flex-col justify-center items-center">
      <div><u>Name:</u> 
      <%= @teacher.full_name %>
      </div>
      <div><u>Contact Number:</u>  
      <%= @teacher.contact_no %>
      </div>
    </div>
    <div class="px-2 flex flex-col justify-center items-center border-r border-l border-slate-500">
      <div><u>Address:</u> 
      <%= @teacher.full_address %>
      </div>
      <div><u>Joining date:</u> 
      <%= @teacher.joining_date %>
      </div>
    </div>
    <div class="px-2 flex flex-col justify-center items-center">
      <div><u>Residing in staff quarter?</u>
      <%= @teacher.staff_quarter %>
      </div>
    </div>
  </div>

  <div class="mt-4 flex justify-center items-center space-x-2">
    <%= link_to edit_teacher_path(@teacher), data: {turbo_frame: "teacher_new_edit_modal" }, class: "px-1 bg-gray-800 rounded-lg text-gray-100 flex justify-center items-center" do %>
      edit
    <% end %>
    <%= link_to teachers_path, class: "px-1 bg-gray-800 rounded-lg text-gray-100 justify-center items-center" do %>
      close
    <% end %>
  </div>
</div>
<% end %>

app/views/teachers/show.html.erb
<%= turbo_frame_tag(dom_id(@teacher)) do %>
  <div class="border-t-4 border-green-600 rounded-xl text-4xl font-light text-gray-700 flex justify-center items-baseline space-x-7">
    <div class="pt-4 flex flex-row justify-center items-center space-x-3">
      <span><%= @teacher.full_name %></span>
      <span class="text-gray-700"><%= @svg.html_safe %></span>
    </div>
    <%= link_to "close", teachers_path, class: "px-2 py-1 rounded bg-gray-700 text-base text-gray-100" %>
  </div>

  <div class="mt-8 flex flex-col justify-center items-center">
    <div class="text-3xl font-extralight">Workload per term:</div>
      <table class="mt-8 table-auto">
        <thead>
          <tr>
            <th class="p-1 border-2 border-gray-400">Subject</th>
            <th class="p-1 border-2 border-gray-400">Book</th>
            <th class="p-1 border-2 border-gray-400">Credits</th>
            <th class="p-1 border-2 border-gray-400">Term</th>
            <th class="p-1 border-2 border-gray-400">Start Date</th>
            <th class="p-1 border-2 border-gray-400">End Date</th>
            <th class="p-1 border-2 border-gray-400">Time</th>
            <th class="p-1 border-2 border-gray-400">Days</th>
            <th class="p-1 border-2 border-gray-400">Classroom</th>
            <th class="p-1 border-2 border-gray-400">Remarks</th>
          </tr>
        </thead>
        <% @teacher_terminal_subjects_without_duplication.each do |classroom_subject| %>
          <tbody>
            <tr>
              <td class="p-1 border-2 border-gray-300"><%= classroom_subject.subject.name %></td>
              <td class="p-1 border-2 border-gray-300"><%= classroom_subject.subject.book %></td>
              <td class="p-1 border-2 border-gray-300"><%= classroom_subject.subject.credits %></td>
              <td class="p-1 border-2 border-gray-300"><%= classroom_subject.term.name %></td>
              <td class="p-1 border-2 border-gray-300"><%= classroom_subject.term.start_date.inspect %></td>
              <td class="p-1 border-2 border-gray-300"><%= classroom_subject.term.end_date.inspect %></td>
              <% if !!classroom_subject.period_time %>
                <td class="p-1 border-2 border-gray-300"><%= classroom_subject.period_time.strftime("%I:%M") %></td>
              <% else %>
                <td class="p-1 border-2 border-gray-300">-</td>
              <% end %>
              <td class="p-1 border-2 border-gray-300"><%= classroom_subject.start_day %> - <%= classroom_subject.end_day %></td>
              <td class="p-1 border-2 border-gray-300"><%= classroom_subject.classroom.name %></td>
              <td class="p-1 border-2 border-gray-300"><%= classroom_subject.remarks %></td>
            </tr>
          </tbody>
        <% end %>
      </table>
    </div>
    <div class="flex flex-col justify-center items-center">
      <%= link_to workload_teacher_path(@teacher, format: :xlsx), class: "mt-2 bg-blue-600 px-2 py-1 text-gray-50 shadow-xl" do %>
        Excel Sheet
      <% end %>
    </div>
    <div class="mt-8 mb-2 border-b-4 pb-4 border-green-600 rounded-xl flex flex-col justify-center items-center">
      <div class="text-3xl font-extralight">Performance in each subject</div>
        <table class="mt-8 table-auto">
          <thead>
            <tr>
              <th class="p-1 border-2 border-gray-400">Subject</th>
              <th class="p-1 border-2 border-gray-400">Book</th>
              <th class="p-1 border-2 border-gray-400">Credits</th>
              <th class="p-1 border-2 border-gray-400">Term</th>
              <th class="p-1 border-2 border-gray-400">Start Date</th>
              <th class="p-1 border-2 border-gray-400">End Date</th>
              <th class="p-1 border-2 border-gray-400">Student</th>
              <th class="p-1 border-2 border-gray-400">Total Marks</th>
            </tr>
          </thead>
          <% @teacher_terminal_subjects.each do |classroom_subject| %>
            <tbody>
              <tr>
                <td class="p-1 border-2 border-gray-300"><%= classroom_subject.subject.name %></td>
                <td class="p-1 border-2 border-gray-300"><%= classroom_subject.subject.book %></td>
                <td class="p-1 border-2 border-gray-300"><%= classroom_subject.subject.credits %></td>
                <td class="p-1 border-2 border-gray-300"><%= classroom_subject.term.name %></td>
                <td class="p-1 border-2 border-gray-300"><%= classroom_subject.term.start_date.inspect %></td>
                <td class="p-1 border-2 border-gray-300"><%= classroom_subject.term.end_date.inspect %></td>
                <td class="p-1 border-2 border-gray-300"><%= classroom_subject.student.first_name + " " + classroom_subject.student.last_name %></td>
                <% if classroom_subject.marks_report.present? %>
                  <td class="p-1 border-2 border-gray-300"><%= classroom_subject.marks_report.total %></td>
                <% end %>
              </tr>
            </tbody>
          <% end %>
        </table>
      </div>
    </div>
  </div>
<% end %>