config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  resources :admins

  # devise_for :admins, controllers: {
  #   sessions: 'users/sessions'
  # }

  # devise_scope :admin do
  #   # Redirests signing out users back to sign-in
  #   get "admins", to: "devise/sessions#new"
  # end

  # get 'classrooms/index'

  root "static_pages#home"

  # get 'sessions/new', as: "log_in"
  
  resources :students do
    member do
      get :profile
    end
    
    collection do
      post :search
    end
  end

  resources :students, only: [:show] do
    resources :terms do
      resources :student_terminal_subjects do
        collection do
          get "time_table", to: "student_terminal_subjects#time_table"
        end
      end
      resources :student_terminal_cocurriculums
    end
  end

  resources :subjects do
    collection do
      get "subjects-excel", to: "subjects#subjects_excel_sheet"
    end
  end

  resources :teachers do
    member do
      get "profile", to: "teachers#profile"
      get "workload", to: "teachers#workload"
    end
  end

  resources :classrooms do
    member do
      post :search_for_attendance
      post :search_for_timetable
    end
    collection do
      get "excel-sheet", to: "classrooms#excel_index"
    end
  end

  resources :student_terminal_subjects, only: [:show] do
    resources :marks_report
  end

  resources :cocurriculums
  
end

app/models/student_terminal_subject.rb
class StudentTerminalSubject < ApplicationRecord
  belongs_to :student
  belongs_to :subject
  belongs_to :teacher
  belongs_to :term
  belongs_to :classroom
  has_one :marks_report, dependent: :destroy

  after_create_commit { broadcast_append_to("student_terminal_subjects_list") }
  after_update_commit { broadcast_update_to("student_terminal_subjects_list") }
  after_destroy_commit { broadcast_remove_to("student_terminal_subjects_list") }
end

app/controllers/student_terminal_subjects_controller.rb
class StudentTerminalSubjectsController < ApplicationController

  def index
    @student = Student.find(params[:student_id])
    @term = Term.find(params[:term_id])
    @student_terminal_subjects = @student.student_terminal_subjects.where(term_id: @term.id).order(subject_id: :asc)
    @student_terminal_cocurriculums = @student.student_terminal_cocurriculums.where(term_id: @term.id).order(id: :asc)
    respond_to do |format|
      format.html
      format.pdf do
        pdf = StudentTerminalSubjectsPdf.new(@student, @term, @student_terminal_subjects)
        send_data pdf.render,
          filename: "#{@student.first_name + " " + @student.second_name + " " + @student.last_name + "-" + @student_terminal_subjects.first.term.name + "-" + @student_terminal_subjects.first.term.end_date.strftime("%B %Y") }.pdf",
          type: 'application/pdf',
          disposition: 'inline'
      end
    end
  end

  def time_table
    @student = Student.find(params[:student_id])
    @term = Term.find(params[:term_id])
    @student_terminal_subjects = @student.student_terminal_subjects.where(term_id: @term.id).order(period_time: :asc)
    render xlsx: "time_table", filename: "#{@student.first_name + " " + @student.second_name + " " + @student.last_name}", disposition: 'inline', template: "student_terminal_subjects/time_table"
  end

  def show
    @student = Student.find(params[:student_id])
    @term = Term.find(params[:term_id])
    @student_terminal_subject = StudentTerminalSubject.find(params[:id])
  end

  def edit
    @student = Student.find(params[:student_id])
    @term = Term.find(params[:term_id])
    @student_terminal_subject = StudentTerminalSubject.find(params[:id])
  end

  def update
    @student = Student.find(params[:student_id])
    @term = Term.find(params[:term_id])
    @student_terminal_subject = StudentTerminalSubject.find(params[:id])

    if @student_terminal_subject.update(student_terminal_subjects_params)
      render @student_terminal_subject
      # respond_to do |format|
      #   format.turbo_stream
      #   format.html { redirect_to student_term_student_terminal_subjects_url(@student, @term) }
      # end
    else
      render :edit
    end
  end

  def new
    @student = Student.find(params[:student_id])
    @term = Term.find(params[:term_id])
    @student_terminal_subject = StudentTerminalSubject.new
  end

  def create
    @student = Student.find(params[:student_id])
    @term = Term.find(params[:term_id])
    @student_terminal_subject = StudentTerminalSubject.new(student_terminal_subjects_params)
    @student_terminal_subject.student_id = @student.id
    @student_terminal_subject.term_id = @term.id

    if @student_terminal_subject.save
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to student_term_student_terminal_subjects_url(@student, @term) }
      end
    else
      render :new
    end
  end

  def destroy
    @student_terminal_subject = StudentTerminalSubject.find(params[:id])

    if @student_terminal_subject.destroy
      respond_to do |format|
        format.turbo_stream
      end
    end
  end

  private

  def student_terminal_subjects_params
    params.require(:student_terminal_subject).permit(:teacher_id, :subject_id, :classroom_id, :period_time, :start_day, :end_day, :remarks)
  end
end

app/helpers/student_terminal_subjects_helper.rb
module StudentTerminalSubjectsHelper
end

app/views/student_terminal_subjects/_credits_count.html.erb
<%= turbo_frame_tag "credits_for_#{@student.id}_in_#{term.id}" do %>
  <%# <div>Total Credits taken by  in <%= student.first_name <%= term.name %><%#: <u>%>
  <div class="px-1 rounded-xl bg-white text-gray-700 border border-cyan-600 text-sm font-bold"><%= student.credits_in_current_term(student, term) %></div>
  <%# </u></div> %>
<% end %>

app/views/student_terminal_subjects/_form.html.erb
<%= form_for([student, term, student_terminal_subject], html: {class: "flex flex-col space-y-2" }) do |f| %>
  <%# <%= f.error_notification message: f.object.errors[:base].to_sentence %>
  <% if student_terminal_subject.errors.any? %>
    <div>Errors:</div>
    <ul>
      <% student_terminal_subject.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <% unless @term.name === "Entrance" || @term.name === "Already Finished" %>
    <%= f.label :period_time, class: "mr-1 text-sm text-gray-700 font-semibold" %>
    <%= f.time_field :period_time, class: "mr-1 px-1 py-1 text-sm text-gray-700 rounded border border-gray-300 bg-gray-200" %>

    <%= f.label :start_day, "From:", class: "mr-1 text-sm text-gray-700 font-semibold" %>
    <%= f.select :start_day, ["Mon", "Tue", "Wed", "Thur", "Fri", "Sat"], {}, class: "mr-1 px-1 py-1 text-sm text-gray-700 rounded border border-gray-300 bg-gray-200" %>

    <%= f.label :end_day, "To", class: "mr-1 text-sm text-gray-700 font-semibold"%>
    <%= f.select :end_day, ["Mon", "Tue", "Wed", "Thur", "Fri", "Sat"], {include_blank: " "}, class: "mr-1 px-1 py-1 text-sm text-gray-700 rounded border border-gray-300 bg-gray-200"  %>

    <%= f.label :remarks, class: "mr-1 text-sm text-gray-700 font-semibold"%>
    <%= f.text_field :remarks, class: "mr-1 px-1 py-1 text-sm text-gray-700 rounded border border-gray-300 bg-gray-200" %>
  <% end %>

  <%= f.label :classroom_id, "Classroom", class: "mr-1 text-sm text-gray-700 font-semibold" %>
  <%= f.collection_select :classroom_id, Classroom.order(:name), :id, :name, {include_blank: " "}, {class: "mr-1 px-1 py-1 text-sm text-gray-700 rounded border border-gray-300 bg-gray-200"} %>
  <%# <%= f.select :classroom_id, Classroom.all %>

  <%= f.label :teacher_id, "Teacher", class: "mr-1 text-sm text-gray-700 font-semibold" %>
  <%= f.collection_select :teacher_id, Teacher.order(:full_name), :id, :full_name, {include_blank: ""}, class: "mr-1 px-1 py-1 text-sm text-gray-700 rounded border border-gray-300 bg-gray-200" %>
  <%# <%= f.input :teacher_id, collection: Teacher.all %>

  <%= f.label :subject_id, "Subject", class: "mr-1 text-sm text-gray-700 font-semibold" %>
  <%= f.collection_select :subject_id, Subject.order(:name), :id, :name, {include_blank: ""}, class: "mr-1 px-1 py-1 text-sm text-gray-700 rounded border border-gray-300 bg-gray-200" %>
  <%# <%= f.input :subject_id, collection: Subject.all %>

  <%= f.submit yield(:button_name), class: "bg-green-600 px-3 py-1 text-sm text-gray-50 rounded-lg hover:bg-green-400" %>
<% end %>

app/views/student_terminal_subjects/_student_terminal_subject.html.erb
<%= turbo_frame_tag(dom_id(student_terminal_subject)) do %>
  <div class="bg-gray-50 px-2 py-1 rounded-lg border border-gray-300 flex justify-center items-center space-x-7">
    <div class="p-2 border border-blue-400 rounded-lg flex flex-col space-y-2">
      <div class="flex flex-row justify-around items-center">
        <div class="font-bold"><%= student_terminal_subject.subject.name %></div>
        <div>
          <%= link_to edit_student_term_student_terminal_subject_url(student_terminal_subject.student, student_terminal_subject.term, student_terminal_subject), class: "text-sm text-blue-500" do %>
            <i class="far fa-edit"></i>
          <% end %>
          
          <%= link_to student_term_student_terminal_subject_url(student_terminal_subject.student, student_terminal_subject.term, student_terminal_subject) , 
                class: "text-sm text-red-500",
                data: { turbo_method: :delete, turbo_confirm: "You are going to delete #{student_terminal_subject.subject.name} for #{student_terminal_subject.student.first_name}"} do %>
                  <i class="far fa-trash-alt"></i>
          <% end %>
        </div>
      </div>

      <div class="flex flex-row text-sm space-x-2">
        <div class=""><%= student_terminal_subject.subject.credits %></div>
        <div class="px-1 border border-green-600"><%= student_terminal_subject.teacher.full_name %></div>
        <div class=""><%= student_terminal_subject.classroom.name %></div>
        <div class=""><%= student_terminal_subject.start_day %> - <%= student_terminal_subject.end_day %></div>
        <% if !!student_terminal_subject.period_time %>
          <div class=""><%= student_terminal_subject.period_time.strftime("%I:%M %p") %></div>
        <% end %>
        <div class=""><%= student_terminal_subject.remarks %></div>
      </div>
    </div>
    
    <div>
      <% if !!student_terminal_subject.marks_report %>
        <%= turbo_frame_tag(dom_id(student_terminal_subject.marks_report)) do %>
          <%= render "marks_report/marks_report", marks_report: student_terminal_subject.marks_report %>
        <% end %>
      <% else %>
        <%= turbo_frame_tag "new_marks_report_for_term#{student_terminal_subject.id}" do %>
          <div class="p-2 border border-indigo-500 rounded-lg flex flex-col justify-center items-center space-y-2">
            <%= link_to new_student_terminal_subject_marks_report_url(student_terminal_subject), class: "px-2 py-1 text-sm bg-green-700 rounded text-gray-50" do %>
              <i class="fa-solid fa-marker"></i> Enter marks
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/student_terminal_subjects/_time_table.html.erb
<div class="mt-4 flex flex-col justify-center items-center">
  <table class="table-auto border-2 border-gray-400">
    <thead>
      <tr>
        <th class="border-2 border-gray-400 px-2 py1">Subject</th>
        <th class="border-2 border-gray-400 px-2 py1">Credits</th>
        <th class="border-2 border-gray-400 px-2 py1">Teacher</th>
        <th class="border-2 border-gray-400 px-2 py1">Classroom</th>
        <th class="border-2 border-gray-400 px-2 py1">Days</th>
        <th class="border-2 border-gray-400 px-2 py1">Time</th>
        <th class="border-2 border-gray-400 px-2 py1">Remarks</th>
      </tr>
    </thead>
    <tbody>
      <% @student_terminal_subjects.each do |student_terminal_subject| %>
        <tr>
          <td class="border-2 border-gray-400 px-2 py1"><%= student_terminal_subject.subject.name %></td>
          <td class="border-2 border-gray-400 px-2 py1"><%= student_terminal_subject.subject.credits %></td>
          <td class="border-2 border-gray-400 px-2 py1"><%= student_terminal_subject.teacher.full_name %></td>
          <td class="border-2 border-gray-400 px-2 py1"><%= student_terminal_subject.classroom.name %></td>
          <td class="border-2 border-gray-400 px-2 py1"><%= student_terminal_subject.start_day %> - <%= student_terminal_subject.end_day %></td>
          <% if !!student_terminal_subject.period_time %>
           <td class="border-2 border-gray-400 px-2 py1"><%= student_terminal_subject.period_time.strftime("%I:%M %p") %></td>
          <% end %>
          <td class="border-2 border-gray-400 px-2 py1"><%= student_terminal_subject.remarks %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to time_table_student_term_student_terminal_subjects_path(@student, @term, format: :xlsx), class: "mt-2 bg-blue-600 px-2 py-1 text-gray-50 shadow-xl" do %>
    Excel Sheet
  <% end %>
  </div>
</div>

app/views/student_terminal_subjects/create.turbo_stream.erb
<%= turbo_stream.append("student_terminal_subjects", @student_terminal_subject) %>

<%= turbo_stream.update("credits_for_#{@student.id}_in_#{@term.id}") do %>
  <div class="px-1 rounded-xl bg-white text-gray-700 border border-cyan-600 text-sm font-bold"><%= @student.credits_in_current_term(@student, @term) %></div>
<% end %>

app/views/student_terminal_subjects/destroy.turbo_stream.erb
<%= turbo_stream.update(dom_id(@student_terminal_subject)) do %>
  <div class="px-4 py-2 text-sm text-green-700 text-xl flex justify-center items-center">
    <i class="fas fa-check"></i>
  </div>
<% end %>

app/views/student_terminal_subjects/edit.html.erb
<% provide(:button_name, "Edit subject") %>

<%= turbo_frame_tag(dom_id(@student_terminal_subject)) do %>
  <%= render "form", student: @student, term: @term, student_terminal_subject: @student_terminal_subject %>
<% end %>

app/views/student_terminal_subjects/index.html.erb
<%= turbo_frame_tag "admin_student_term_terminal_subjects_#{@term.id}" do %>
  <% if @term.name == 'Entrance' %>
    <% provide(:button_name, "Add Entrance Subject") %>
  <% elsif @term.name == 'Already Finished' %>
    <% provide(:button_name, "Add The Subject Already Finished") %>
  <% else %>
    <% provide(:button_name, "Add New Terminal Subject") %>
  <% end %>

  <div class="flex justify-center">
    <%= link_to student_path(@student), class: "bg-red-500 hover:bg-red-700 px-1 text-sm text-gray-50 rounded-t flex items-center" do  %>
      close this portal
    <% end %>
  </div>

  <div class="bg-slate-200 border-t-2 border-b-2 border-indigo-500 rounded-lg shadow-lg ">
    <div class="flex flex-col justify-center items-center">
      <div class="pt-4 pb-2 text-3xl font-light text-gray-700">Curricular Activities</div>
      <div class="flex justify-center items-center space-x-2">
        <%= link_to student_term_student_terminal_subjects_path(@student, @term, format: :pdf), target: "_blank", class: "px-2 bg-blue-600 rounded text-gray-50 hover:bg-blue-800" do %>
          <i class="fas fa-file-pdf"></i> Marks Report
        <% end %>

        <%= link_to new_student_term_student_terminal_subject_path, data: { turbo_frame: "student_terminal_subject_new_edit_modal" }, class: "px-2 bg-green-600 text-gray-50 rounded hover:bg-green-800" do %>
          <%= yield(:button_name) %>
        <% end %>
      </div>
    </div>

    <%= turbo_stream_from "student_terminal_subjects_list" %>
    <%= turbo_frame_tag "student_terminal_subjects" do %>
      <div class="mt-4 mb-8 flex flex-col justify-center items-center space-y-1">
        <% @student_terminal_subjects.each do |student_terminal_subject| %>
          <%= render "student_terminal_subjects/student_terminal_subject", student_terminal_subject: student_terminal_subject %>
        <% end %>
      </div>
    <% end %>  
  </div>

  <% unless @term.name == 'Entrance' || @term.name == 'Already Finished' %>
  <div class="pt-16 pb-2 bg-red-50">
    <div class="flex flex-col justify-center items-center">
      <div class="pt-4 pb-3 text-3xl font-light text-gray-700 underline">Co-curricular Activities</div>
      <%= link_to new_student_term_student_terminal_cocurriculum_path, data: {turbo_frame: "modal" }, class: "px-3 py-2 bg-green-600 text-gray-50 hover:bg-green-400 rounded-lg" do %>
        Add New Cocurriculum
      <% end %>
    </div>
    <div class="pb-16 flex flex-col justify-center items-center">
      <% if @student_terminal_cocurriculums.any? %>
        <%= turbo_stream_from "student_terminal_cocurriculums_list" %>
        <%= turbo_frame_tag "student_terminal_cocurriculums" do %>
          <% @student_terminal_cocurriculums.each do |student_terminal_cocurriculum| %>
            <%= render "student_terminal_cocurriculums/student_terminal_cocurriculum", student_terminal_cocurriculum: student_terminal_cocurriculum %>
          <% end %>
        <% end %>
      <% else %>
        <div>No Cocurriculums entered</div>
      <% end %>
    </div>
  </div>
  <% end %>

  <% unless @term.name == "Entrance" || @term.name == "Already Finished" %>
    <% if @student_terminal_subjects.any? %>
      <div class="py-8 bg-gray-200">
        <div class="text-3xl font-extralight flex justify-center">
          Time table for: <%= @student.first_name + " " + @student.second_name + " " + @student.last_name %>
          <%= link_to student_path(@student), class: "ml-2 bg-blue-700 hover:bg-blue-900 px-1 text-lg text-gray-50 rounded-xl flex items-center" do  %>
            Show all the terms
          <% end %>
        </div>
        <%= render "student_terminal_subjects/time_table" %>
      </div>
    <% else %>
      <div class="py-8 mt-8 bg-gray-100">
        <div class="text-3xl font-extralight flex justify-center items-center">
          No time table for: <%= @student.first_name %>  
          <%= link_to student_path(@student), class: "ml-2 bg-blue-700 hover:bg-blue-900 px-1 text-lg text-gray-50 rounded-xl flex items-center" do  %>
            Show all the terms
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
  <div class="flex justify-center">
      <%= link_to student_path(@student), class: "bg-red-500 hover:bg-red-700 px-1 text-sm text-gray-50 rounded-b flex items-center" do  %>
        close this portal
      <% end %>
    </div>
<% end %>

app/views/student_terminal_subjects/new.html.erb
<% provide(:button_name, "Add subject") %>

<%= turbo_frame_tag "student_terminal_subject_new_edit_modal" do %>
  <div data-controller="form-modal" data-action="turbo:submit-end->form-modal#submitEnd">
    <div class="min-h-screen w-screen bg-black bg-opacity-80 flex justify-center items-center fixed z-10">
      <%= link_to student_term_student_terminal_subjects_path(@student, @term), class: "mx-2 text-xl text-gray-100 absolute top-10 right-80" do %>
        <i class="fa-solid fa-circle-xmark"></i>
      <% end %>
      <div class="bg-white px-20 py-6 rounded shadow-2xl">
        <div class="text-lg text-gray-800">New Curriculum</div>
        <%= render "form", student: @student, term: @term, student_terminal_subject: @student_terminal_subject %>
      </div>
    </div>
  </div>
<% end %>